# Generated by Django 4.1.2 on 2022-11-06 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tarea', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familiares',
            old_name='edad',
            new_name='telefono',
        ),
    ]
